TARGET = libpedsim.so
SOURCES = $(shell echo *.cpp)
OBJECTS = $(SOURCES:.cpp=.o)
CXXFLAGS = -fPIC -shared -lm -fopenmp -march=native -DNOCUDA -g -DCMAKE_EXPORT_COMPILE_COMMANDS=1

all: $(TARGET)

$(TARGET): $(OBJECTS)
	$(CXX) $(FLAGS) $(CXXFLAGS) $(DEBUGFLAGS) -o $(TARGET) $(OBJECTS)



clean:
	-rm $(TARGET) $(OBJECTS)
